sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
  - '5'
  - '10'
before_install:
  - npm i -g npm@^2.0.0
install:
  - npm i -g codecov codeclimate-test-reporter
  - npm i
before_script:
  - npm prune
script:
  - npm run travis
  - codecov
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
